name: Run Selenium Tests on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Устанавливаем Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Запускаем HTTP-сервер и тесты
      - name: Start local HTTP server and run tests
        shell: pwsh
        run: |
          # Запуск сервера из папки tests
          Start-Process -NoNewWindow -WorkingDirectory "${{ github.workspace }}/tests" -FilePath python -ArgumentList "-m http.server 8000"
          # Ждём, чтобы сервер успел подняться
          Start-Sleep -s 5
          # Запуск pytest
          pytest --maxfail=1 --disable-warnings -v
